#!/bin/bash
#Script to run the 0D BFM17 code
#
#-----SET THE BFM DIRECTORY----
#
export PATH=/usr/bin:$PATH
export BFMdir=./
export NETCDF="/usr/local/netcdf/"
#
#-----ENTER BFM-----
#
cd $BFMdir
pwd
#
#-----CLEANING-----
#
cd run
rm standalone.pelagic/*
rmdir standalone.pelagic
cd ..
#
#-----GENERATE COMPILE AND DEPLOY BFM-----
#
cd $BFMdir/build
./bfm_configure.sh -gcd
cd ..
#
#-----EXECUTE-----
#
cd $BFMdir/run/standalone.pelagic
echo "I AM IN STANDALONE.PELAGIC"
pwd
ls
./*.x
#
pwd
ls
#
